sudo: required

services:
  - docker

env:
  global:
    - LIBUSB_VERSION=v1.0.22
    - ADK_PLATFORM_TOOLS_VERSION=28.0.0
  matrix:
    - DISTRIBUTION=bionic
    - DISTRIBUTION=xenial

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

script:
  - echo Packaging adb from platform-tools version $ADK_PLATFORM_TOOLS_VERSION for $DISTRIBUTION
  - docker --version
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - docker build --build-arg LIBUSB_VERSION=$LIBUSB_VERSION --build-arg ADK_PLATFORM_VERSION=$ADK_PLATFORM_VERSION -t quamotion/adb:$ADK_PLATFORM_TOOLS_VERSION-$DISTRIBUTION $DISTRIBUTION

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker push quamotion/adb:$ADK_PLATFORM_TOOLS_VERSION-$DISTRIBUTION
